name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable corepack / set pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.0.0 --activate
      - name: Install
        run: pnpm -w install --no-frozen-lockfile
      - name: Build site
        run: pnpm -C app/packages/site build
